//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGereciamentoPedidos
{


	public partial class SiteMaster
	{

		/// <summary>
		/// Head control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.ContentPlaceHolder Head;

		/// <summary>
		/// MainContent control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;

		/// <summary>
		/// MasterPageToast control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::WebGereciamentoPedidos.src.components.Toast.Toast MasterPageToast;

		/// <summary>
		/// MasterPageModalConfirmacaoExclusao control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::WebGereciamentoPedidos.src.components.ModalConfirmacaoExclusao.ModalConfirmacaoExclusao MasterPageModalConfirmacaoExclusao;

		/// <summary>
		/// MasterPageLoadingModal control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::WebGereciamentoPedidos.src.components.LoadingModal MasterPageLoadingModal;

		/// <summary>
		/// PageScripts control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.ContentPlaceHolder PageScripts;
	}
}
