//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGereciamentoPedidos.src.pages.ItemPedidoPages.FormAddEditItemPedido
{


	public partial class FormAddEditItemPedido
	{

		/// <summary>
		/// PesquisaLookUpProdutos control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::WebGereciamentoPedidos.src.pages.ProdutoPages.PesquisaLookUpProdutos.PesquisaLookUpProdutos PesquisaLookUpProdutos;

		/// <summary>
		/// FormAddEditItemPedidoPanel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel FormAddEditItemPedidoPanel;

		/// <summary>
		/// FormAddEditItemPedidoTituloMedio control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::WebGereciamentoPedidos.src.components.TituloMedio.TituloMedio FormAddEditItemPedidoTituloMedio;

		/// <summary>
		/// ProdutoTextFormField control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::WebGereciamentoPedidos.src.components.TextFormField ProdutoTextFormField;

		/// <summary>
		/// PesquisarProdutoButton control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Button PesquisarProdutoButton;

		/// <summary>
		/// QtdeTextFormField control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::WebGereciamentoPedidos.src.components.TextFormField QtdeTextFormField;

		/// <summary>
		/// CancelarItemPedidoButton control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Button CancelarItemPedidoButton;

		/// <summary>
		/// SalvarItemPedidoButton control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Button SalvarItemPedidoButton;
	}
}
