//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGereciamentoPedidos.src.pages.PedidoPages.FormAddEditPedido
{


	public partial class FormAddEditPedido
	{

		/// <summary>
		/// MestreDetalhePedidoPanel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel MestreDetalhePedidoPanel;

		/// <summary>
		/// FormAddEditPedidoPanel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel FormAddEditPedidoPanel;

		/// <summary>
		/// FormAddEditPedidoTituloMedio control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::WebGereciamentoPedidos.src.components.TituloMedio.TituloMedio FormAddEditPedidoTituloMedio;

		/// <summary>
		/// ClienteTextFormField control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::WebGereciamentoPedidos.src.components.TextFormField ClienteTextFormField;

		/// <summary>
		/// VlrSubtotalTextFormField control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::WebGereciamentoPedidos.src.components.TextFormField VlrSubtotalTextFormField;

		/// <summary>
		/// DescontoTextFormField control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::WebGereciamentoPedidos.src.components.TextFormField DescontoTextFormField;

		/// <summary>
		/// VlrTotalTextFormField control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::WebGereciamentoPedidos.src.components.TextFormField VlrTotalTextFormField;

		/// <summary>
		/// MetodoPagtoDropDownList control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::WebGereciamentoPedidos.src.components.GPDropDownList.GPDropDownList MetodoPagtoDropDownList;

		/// <summary>
		/// DataHoraPedidoDataPicker control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::WebGereciamentoPedidos.src.components.DataPicker.DataPicker DataHoraPedidoDataPicker;

		/// <summary>
		/// StatusDropDownList control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::WebGereciamentoPedidos.src.components.GPDropDownList.GPDropDownList StatusDropDownList;

		/// <summary>
		/// ObservacoesTextFormField control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::WebGereciamentoPedidos.src.components.TextFormField ObservacoesTextFormField;

		/// <summary>
		/// CancelarPedidoButton control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Button CancelarPedidoButton;

		/// <summary>
		/// SalvarPedidoButton control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Button SalvarPedidoButton;

		/// <summary>
		/// DetalhesItensDoPedidoPanel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel DetalhesItensDoPedidoPanel;

		/// <summary>
		/// ListagemItensDoPedido control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::WebGereciamentoPedidos.src.pages.ItemPedidoPages.ListagemItensDoPedido.ListagemItensDoPedido ListagemItensDoPedido;
	}
}
