//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGereciamentoPedidos.src.pages.ItemPedidoPages.ListagemItensDoPedido
{


	public partial class ListagemItensDoPedido
	{

		/// <summary>
		/// ItensPedidoTitulo control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::WebGereciamentoPedidos.src.components.TituloMedio.TituloMedio ItensPedidoTitulo;

		/// <summary>
		/// ItensPedidosGW control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.GridView ItensPedidosGW;
	}
}
